k8s_masters:
  hosts:
    # master nodes
    master-node1:
      ansible_host: 192.168.95.70
    master-node2:
      ansible_host: 192.168.95.71
    master-node3:
      ansible_host: 192.168.95.72
#k8s_workers:
#  hosts:
    # Worker nodes
    #worker-node1:
    #  ansible_host: 192.168.95.75
k8s_cluster:
  children:
    k8s_masters:
    #k8s_workers:
