---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - keepalived
      - haproxy
    state: present
  when: 
    - inventory_hostname == groups['k8s_masters']

- name: Copy keepalived.conf to master
  template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
  register: keepalived_conf
  when: 
    - inventory_hostname == groups['k8s_masters']

- name: Copy haproxy haproxy.cfg
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
  register: haproxy_conf
  when: 
    - inventory_hostname == groups['k8s_masters']

- name: Enable keepalived and haproxy
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - keepalived
    - haproxy
  when: 
    - inventory_hostname == groups['k8s_masters']

- name: Restart keepalived
  service:
    name: keepalived
    state: restarted
  when: 
    - keepalived_conf.changed
    - inventory_hostname == groups['k8s_masters']

- name: Restart haproxy
  service:
    name: haproxy
    state: restarted
  when: 
    - haproxy_conf.changed
    - inventory_hostname == groups['k8s_masters']