- name: Create /etc/kubernetes/ directory
  ansible.builtin.file:
    path: /etc/kubernetes/
    state: directory
    mode: '0755'

- name: copy kubeadm config file
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm.conf
    mode: '0644'
  when: 
    - inventory_hostname == groups['k8s_masters']

- name: Check if Kubernetes cluster is initialized
  command: kubectl cluster-info
  register: cluster_info
  when: inventory_hostname == groups['k8s_masters'][0]
  ignore_errors: true
  changed_when: false

- name: Initialize first Kubernetes master node
  ansible.builtin.command: kubeadm init --config /etc/kubernetes/kubeadm.conf
  when: 
    - inventory_hostname == groups['k8s_masters'][0]
    - cluster_info.failed

- name: Make .kube directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0700'
  when: 
    - inventory_hostname == groups['k8s_masters']

- name: Copy admin.conf 
  ansible.builtin.copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
    mode: '0644'
  when: 
    - inventory_hostname == groups['k8s_masters'][0]

- name: Prepare to Join another master node
  include_tasks: certs.yaml
  when: 
    - inventory_hostname == groups['k8s_masters'][0]

- name: Get list of current nodes
  shell: kubectl get nodes -o jsonpath='{.items[*].metadata.name}'
  register: nodes_list
  when: inventory_hostname == groups['k8s_masters'][0]
  run_once: true

- name: Join master nodes
  shell: 
    cmd: |
      kubeadm join {{ hostvars[groups['k8s_masters'][0]].join_path.stdout }} \
      --token {{ hostvars[groups['k8s_masters'][0]].join_token.stdout }} \
      --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_masters'][0]].discovery_token_ca_cert_hash.stdout }} \
      --control-plane --certificate-key {{ hostvars[groups['k8s_masters'][0]].certificate_key.stdout }}
  when: 
    - inventory_hostname not in nodes_list.stdout
    - inventory_hostname != groups['k8s_masters'][0]
